### ISSUE TITLE
Error on ?input=http://url/?files=....

### ISSUE THREAD

**Issue by xeonfeng** [ivmartel/dwv-jqmobile#21]
When I using "npm run start" run the dvm website ,by using expamle url files( http://localhost:8080/index.html?input=https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/?file=bbmri-53323851.dcm&file=bbmri-53323707.dcm&file=bbmri-53323563.dcm&file=bbmri-53323419.dcm&file=bbmri-53323275.dcm&file=bbmri-53323131.dcm&dwvReplaceMode=void) ,then get the following error:  RequestError: Error status: 400 while loading 'https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/?file' [DicomDataLoader]

![image](https://user-images.githubusercontent.com/11417207/57495997-52a2ae00-7303-11e9-885b-fb7478da5aef.png)

**Comment by ivmartel** [comment]
You need to url encode the input part of the url so that dwv does not try to interpret it. 

Your input part: `https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/?file=bbmri-53323851.dcm&file=bbmri-53323707.dcm&file=bbmri-53323563.dcm&file=bbmri-53323419.dcm&file=bbmri-53323275.dcm&file=bbmri-53323131.dcm`

Becomes: `https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm`

So the final url is: `http://localhost:8080/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void` (`dwvReplaceMode` is not in the input part)

**Comment by xeonfeng** [comment]
Thanks! I had got the solution after the question a few mintinus.
